### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#14]
@OstapL я зробила сторінку 404

- [x] потрібно зверстати за макетом

**Comment by ratmirasanov** [comment]
@OstapL, что тут осталось? Прикрутить страницу, чтобы показывало в случае невалидных ссылок?

**Comment by OstapL** [comment]
@ratmirasanov да но это к Владу

**Comment by ratmirasanov** [comment]
@vladyslav2, сделай, плиз, чтобы показывалась страница 404 в случае открытия несуществующих страниц на сайте.

**Comment by vladyslav2** [comment]
@ratmirasanov сделал, проверь

**Comment by MariaKravchuk** [comment]
@OstapL 

- [ ] додай відступ між кратинками і буквами.
![2017-11-23 20 04 43](https://user-images.githubusercontent.com/20995691/33185200-ac642004-d089-11e7-9db2-6154c65c9efe.png)

**Comment by OstapL** [comment]
@vladyslav2 ну ты открыл путь на картинку 
если просто перейти на несуществующую страницу то все норм 
https://webdevelop.pro/lakwjdl
