### ISSUE TITLE
Metatags for SEO on each page

### ISSUE THREAD

**Issue by ratmirasanov** [OstapL/wdev#17]
- [x] страница index.html:
      title: 'Webdevelop Pro'.
      description: 'Web development, Mobile development, UI/UX development, Speed optimization, Ongoing Support, Consulting and Audit'.

- [x] страница contact.html:
      title: 'Contacts'.
      description: 'Webdevelop Pro contact information'.

- [x] страница portfolio.html:
      title: 'Portfolio'.
      description: 'Web development portfolio'.

- [x] страница iolinteractive.html:
      title: 'IOLinteractive'.
      description: 'Viral marketing tool. Landing, python, debian, bootstrap, advertising, digitalocean, sentry, django'.

- [x] страница multi-level-marketing.html:
      title: 'Multi-level marketing'.
      description: 'Pyramid-style Marketing Approach. MLM, marketing, dashboard, python, backend, dwolla, firstdata, payouts commissions, unittest, django, django-mptt'.

- [x] страница domain-system.html:
      title: 'Domain system'.
      description: 'Site Valuation Calculator. Nodejs, seo, network, fullstack, foundation, microservices, mongodb, redis, scale'.

- [x] страница who-we-are.html:
      title: 'About Webdevelop Pro'.
      description: 'Webdevelop Pro's team members. Vlad Tarasenko, Maria Kravchuik, Ostap Lazoryak, Ratmir Asanov, Sergey Nikolenko, Dmytro Sapotnitski'.

- [x] страница blog-list.html:
      title: 'Blog'.
      description: 'Web development blog'.

- [x] страница single-post.html:
      title: 'Нехай пишеться назва статті'.
      description: 'Теги із статті через кому і без решітки'.

- [x] страница 404.html:
      title: '404'.
      description: 'Page not found'.

**Comment by ratmirasanov** [comment]
@vladyslav2, @MariaKravchuk, написал какие у нас страницы и какие данные по SEO. Надо подумать над текстами.

**Comment by ratmirasanov** [comment]
@vladyslav2, поменял чуток текста и пушнул.

**Comment by MariaKravchuk** [comment]
@ratmirasanov @vladyslav2 прохання не міняти текста, а зробити так як написано тут в тікеті!!!!

Ще раз провіряєте, поправляєте за тікетом і закриваєте)

**Comment by MariaKravchuk** [comment]
- [ ] для @MariaKravchuk підготувати картинки, які потрібно підтягувати при надсиланні ссилок та іншого шарінгу сторінок.

**Comment by vladyslav2** [comment]
@ratmirasanov вернул назад заголовки, если ты считаешь что твои были более правильные то это нужно обсудить/написать тут в тикете

**Comment by MariaKravchuk** [comment]
@vladyslav2 чекни тут кожний заголовок який вернув)
