### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#2]
- [x] постав фавіконку в таб
https://drive.google.com/open?id=1zGG4Y9I29efer6SbkmldlfiMjyS78UbW

- [x] перевірити типографіку (величини тайтлів, лайнхейт і тд).

- [x] Анімація скролу вниз. Іконку треба анімувати та сам скрол зробити плавним перенаправленням. 

- [x] зараз іконка скролу внизу якось обрізана на половину, наче не влазить

@vladyslav2, приклад як анімувати іконку https://codemyui.com/scroll-icon-animation/
Тільки замість кружечка в нас буде полоска.

- [x] сірий колір перевір по макету (іконки, текст)

- [x] перевір товщину полоски за макетом -- має бути більшою:
![2017-10-24 19 13 29](https://user-images.githubusercontent.com/20995691/31954904-7bbf22b6-b8ef-11e7-83de-548f630b3e69.png)

- [x] коли наводиш на інший елемент не потрібно знизу полоски. Нехай з'явдяється тільки при клікові:
![2017-10-24 19 14 47](https://user-images.githubusercontent.com/20995691/31955028-d7719486-b8ef-11e7-8722-5d07dc768d11.png)

- [x] полоску при наведенні забираємо, але іконку давай робити сірою. І роби сірий колір з макету. (скріншот з макету)
![2017-11-08 15 21 58](https://user-images.githubusercontent.com/20995691/32551265-98854bf0-c498-11e7-9485-cdf0dc37514e.png)

- [x] вирівняй плейсхолдер
![2017-11-08 15 30 32](https://user-images.githubusercontent.com/20995691/32551637-d9896c5c-c499-11e7-8a3d-53578931af2c.png)

- [x] тут перевірити типографіку:
![2017-10-24 19 16 51](https://user-images.githubusercontent.com/20995691/31955127-20c7e0cc-b8f0-11e7-8d44-76f47a8d1c6d.png)

- [x] не треба сірим кольром робити міста
![2017-11-08 15 29 10](https://user-images.githubusercontent.com/20995691/32551565-a96fe58c-c499-11e7-8f8e-481f43190b50.png)

- [x] до ховрашка треба додати слово GO (див макет), і він має бути блакитним:
![2017-10-24 19 20 09](https://user-images.githubusercontent.com/20995691/31955248-8310107e-b8f0-11e7-9e7d-01f55e16f51b.png)

- [x] тут пропоную поставити іконку скетча - https://www.google.com.ua/search?q=icon+sketch&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjXiuHGia_XAhXRo6QKHelFABAQ_AUICigB&biw=1440&bih=713#imgrc=0hh9Z5DBrS-TkM:
(https://user-images.githubusercontent.com/20995691/31955282-9801d4a4-b8f0-11e7-9791-48a498c21fd8.png)

- [x] у футері треба зробити картинку на дві секції:
![2017-10-24 19 23 03](https://user-images.githubusercontent.com/20995691/31955361-d2febaa4-b8f0-11e7-92d3-fe2c9ca699fa.png)

- [x] при ховері треба додати до ссилок якийсь ефект, наприклад сірим:
![2017-10-24 19 24 11](https://user-images.githubusercontent.com/20995691/31955490-3c7edc70-b8f1-11e7-8bfa-60c4fa405e6d.png)

- [x] давайте заберемо можливість розтягувати інпут тут:
![2017-10-24 19 29 46](https://user-images.githubusercontent.com/20995691/31955687-cf48e2ee-b8f1-11e7-8898-76fc6fe6f838.png)

- [x] зробіть валідацію до форми -- зараз можна відправити незаповнивши всі дані.

**Comment by vladyslav2** [comment]
- [ ] убрать синий border после нажатия таба ![screen shot 2017-11-08 at 5 48 38 pm](https://user-images.githubusercontent.com/704096/32558488-85ac087e-c4ad-11e7-964c-5a881d9b8d88.png)

**Comment by vladyslav2** [comment]
- [ ] @MariaKravchuk @OstapL оформить и поправить сообщения об ошибках
![screen shot 2017-11-08 at 5 52 31 pm](https://user-images.githubusercontent.com/704096/32558534-a65febc6-c4ad-11e7-9e4c-bac97bfb6a66.png) при нажатии кнопке отправить когда не заполненны все данные

**Comment by vladyslav2** [comment]
- [ ] 1200x600 - не видно кнопки скрола
![screen shot 2017-11-08 at 5 54 34 pm](https://user-images.githubusercontent.com/704096/32558645-f5db1e50-c4ad-11e7-97e1-7af64fbe056d.png)

**Comment by triamazikamno** [comment]
"to those, who will not be visible"
who не говорят о неодушевленных вещах :)
Что вообще хотелось сказать этим предложением?

**Comment by vladyslav2** [comment]
@triamazikamno мы следим за всеми элементами разработки, даже за теми, которые не видны обычным пользователям

**Comment by triamazikamno** [comment]
Perfection is not attainable, but we're passionate about all parts of the development process, even if they're not visible to the end user
как-то так, но сама исходная формулировка не очень нативно звучит

**Comment by OstapL** [comment]
@MariaKravchuk 
favicon має бути однакового розміру 
наприклад 64*64

**Comment by MariaKravchuk** [comment]
@OstapL кинула три варіанти 
https://drive.google.com/drive/folders/12CUUQZSgogsBMprr4eA7o2MG6ORLnZti

**Comment by MariaKravchuk** [comment]
- [ ] @vladyslav2 @OstapL після того, як натиснув на send нехайз опасіті появляється такий поп ап
і через пару секунд пропадає
![2017-11-14 21 13 50](https://user-images.githubusercontent.com/20995691/32799535-bb7fe34e-c980-11e7-81d9-3b1e019c4b60.png)

**Comment by MariaKravchuk** [comment]
- [ ] оновити секцію такими іконками (і додамо анімацію до них)
![2017-11-14 21 08 43](https://user-images.githubusercontent.com/20995691/32799588-de9da870-c980-11e7-82bd-3f4a9902766b.png)

- [ ] на моб поправити локації
![2017-11-14 21 15 15](https://user-images.githubusercontent.com/20995691/32799623-f9a6093c-c980-11e7-8ba5-0bea2c6f8a63.png)
