### ISSUE TITLE
Popups html bugs

### ISSUE THREAD

**Issue by vladyslav2** [OstapL/wdev#20]
Сюдя будем писать все тикеты связанные с html и popupами:

- [x] сейчас попап появляется где-то, но не в области видимости (я подозреваю, что он где-то вверху страницы стал показываеться, те там где я не вижу попапа):
<img width="1197" alt="screen shot 2017-11-27 at 11 46 35 pm" src="https://user-images.githubusercontent.com/704096/33291375-45eb7bfe-d3ce-11e7-8e51-535019485ecf.png">

Не могу без этого проверить -- https://github.com/OstapL/wdev/issues/15#issuecomment-347306791.

**Comment by MariaKravchuk** [comment]
@OstapL 

- [ ] коли відкрив відео в галереї, закрив його, то не можеш нікуди проскролити
https://ostaplazoryak.000webhostapp.com/multi-level-marketing.html

- [ ] також оли не нажав на стоп і просто закрив попап - звук далі є чутним

**Comment by MariaKravchuk** [comment]
@OstapL @vladyslav2  @ratmirasanov 
потестуйте попапи на підписку та контактну форму на мобільних. 
що побачила я:

- [ ] після відправки даних не очищаються поля

- [ ] довго не появляється попап - треба по пару раз нажати кнопку, або просто ждати

- [ ] аналогічно не пропадає довго, або взагалі не пропадає
![image](https://user-images.githubusercontent.com/20995691/33620360-4f5cb3d8-d9f0-11e7-98b9-365e0f475a16.png)

**Comment by MariaKravchuk** [comment]
@vladyslav2 

- [ ] коли набираєш 4 символи валідація не зникає

![image](https://user-images.githubusercontent.com/20995691/34079516-dc530512-e337-11e7-949f-d4b33b05103e.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk то все решили?

**Comment by MariaKravchuk** [comment]
@vladyslav2 на сторінці Contacts перевір ще все. Там буває 405 появляється після відправки

- [ ] для моб зроби перенаправлення вверх до попапу який появляється після відправки форми (і для підписки тж це зроби)

**Comment by vladyslav2** [comment]
@ostapl давай посмотрим вместе попап там похоже с css проблема

**Comment by vladyslav2** [comment]
@MariaKravchuk поправил
