### ISSUE TITLE
Mobile bugs (html)

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#24]
- [x] виводь кружечки на центр, якщо так легше зробити. І нехай повертаються на місце, якщо тапнув в іншому місці
![image](https://user-images.githubusercontent.com/20995691/33619463-00643bc2-d9ee-11e7-95d0-c0afcb132786.png)

- [x] тут проиіжки зроби по 50 пкс
![image](https://user-images.githubusercontent.com/20995691/33619568-45562862-d9ee-11e7-8e34-9951b9a7b003.png)

- [x] поправ тут верстку за макетом - паддінги, вирівнювання
![image](https://user-images.githubusercontent.com/20995691/33619629-66b733ac-d9ee-11e7-9f60-baa585fe6204.png)

- [x] поправ розташування тексту за макетом. 
![image](https://user-images.githubusercontent.com/20995691/33619664-7c85ee94-d9ee-11e7-8a95-275d3ff2a569.png)

- [x] переглянь відступи на моб у футері за макетом. Також поміняй на About. І поправ послідовність лінків - About/Portfolio та Contacts/Blog
![image](https://user-images.githubusercontent.com/20995691/33619691-8e3072e0-d9ee-11e7-92c7-a4db5a400224.png)

- [x] забери проміжок між меню і картинкою
![image](https://user-images.githubusercontent.com/20995691/33619722-9fa2430a-d9ee-11e7-88f6-fb8d819bc2bc.png)

- [x] нехай попап з відео відкривається як і в нас на головній на GF було. Або якось по центру і на всю ширину.
![image](https://user-images.githubusercontent.com/20995691/33619798-c65883ce-d9ee-11e7-8bb6-e8532cf380ce.png)
![image](https://user-images.githubusercontent.com/20995691/33619810-ce0b199c-d9ee-11e7-8044-626da2239107.png)

- [x] на мобі давай ховати ці контакти, якщо вони не влазять по боках
![image](https://user-images.githubusercontent.com/20995691/33619865-f01212e8-d9ee-11e7-8388-4fd6b6d7c13f.png)

- [x] тут треба навпаки - після заголовку щоб йшов текст, потім автор і кнопка
![image](https://user-images.githubusercontent.com/20995691/33619898-0cec71a6-d9ef-11e7-8d28-ed7e71bed6d6.png)

- [x] давай на моб ім'я та посаду підніми вверх, а дату знизу. Відповідно щоб вирівнялося по верхньому краю картинки і по нижньому (дата)
![image](https://user-images.githubusercontent.com/20995691/33619965-30aab2b0-d9ef-11e7-974b-10a98eb44971.png)

- [x] шарінг став під теги
![image](https://user-images.githubusercontent.com/20995691/33619984-4173cca8-d9ef-11e7-814b-c28ec8283402.png)

**Comment by OstapL** [comment]
@MariaKravchuk 
дивись от тут треба робити от так починаючи з планшетів >767px
якось так 
<img width="949" alt="2017-12-10 15 20 41" src="https://user-images.githubusercontent.com/20583571/33805230-147a2ecc-ddbe-11e7-94ec-f05463d76d29.png">
а для телефонів взагалі в стовпчик
<img width="517" alt="2017-12-10 15 22 14" src="https://user-images.githubusercontent.com/20583571/33805232-246618f0-ddbe-11e7-9d8e-aa523cf2d23c.png">
це просто з досвіду адаптивної верстки ) 
тому що як не старайся я на всі девайси не зроблю норм

Такі речі в таких випадках роблять приблизно так як я тобі для прикладу показав

**Comment by MariaKravchuk** [comment]
@OstapL я не проти, зроби це і треба подивитися як воно відкриватиметься. А для планшетів думаю треба якось вліпити на бекграунді Approach і пунктирну полоску.

**Comment by MariaKravchuk** [comment]
@OstapL 

- [ ] перевір відступ тут під заголоком (під полоскою), щось він завеликий
![image](https://user-images.githubusercontent.com/20995691/34079531-2e2a8d38-e338-11e7-8f6a-cea054e2a25b.png)

**Comment by OstapL** [comment]
@MariaKravchuk  да ти права ) завеликий ) ми коли міняли на 80 я для моб не поправив )

**Comment by MariaKravchuk** [comment]
@OstapL перевір на моб ще ці відступи (це є в моб макеті якщо що)

- [ ] внизу кожної сторінки (перед футером, або придеглою до нього секції) має
 бути однаковий відступ 70 пкс
![image](https://user-images.githubusercontent.com/20995691/34122848-66ca87d4-e436-11e7-81fc-a22bea93ae8a.png)

- [ ] під і над кружками зроби однаковий відступ (по 60 пкс)
![image](https://user-images.githubusercontent.com/20995691/34122878-820fcb1c-e436-11e7-9bf0-6abbf883f099.png)

- [ ] для Gf я так зрозуміла ти взяв картинкою шрифти тут. Вони трохи розмазано виглядають, тому експортнула більші розміри (для кольорів, шрифтів і ui) https://drive.google.com/open?id=1UlDZfhsFZruhBmWSlm_tFkwGWJ5v2ace
![image](https://user-images.githubusercontent.com/20995691/34122958-b7069738-e436-11e7-9dd7-1b328fc01e98.png)
