### ISSUE TITLE
Почему на странице блога (и скорее всего других) нет h1 но есть h2?

### ISSUE THREAD

**Issue by vladyslav2** [OstapL/wdev#25]
![screen shot 2017-12-11 at 12 48 38 pm](https://user-images.githubusercontent.com/704096/33827693-db641aa8-de71-11e7-84a8-ec73abddfb36.png)

@OstapL почему h2 а не h1? мы уже же обсуждали это на проекте growthfountain - на странице заголовок нужно делать через h1

**Comment by MariaKravchuk** [comment]
@OstapL @vladyslav2 відразу ж поправте по SEO на цій сторінці. 
Виводьте в табі назву статті
![2017-12-11 12 56 17](https://user-images.githubusercontent.com/20995691/33827926-b7be1350-de72-11e7-8ee0-3858bd389464.png)

**Comment by OstapL** [comment]
@vladyslav2 вопрос не ко мне 
пускай Маша поменяет на h1 я сделаю

**Comment by MariaKravchuk** [comment]
@OstapL в макеті оновила, можеш правити https://drive.google.com/open?id=1c1TAGChBg5p5Ei4uaez3f9VAZEguAghj
