### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#28]
Давайте тут писати все що стосується шарінга

- [x] при пересиланні ссилок усіх на сторінки із сайту нехай підтягується ця картинка 
https://drive.google.com/open?id=19-kr4rjvLjNLL7Hv-ZA4KFF9QTNd7qSI

- [x] при пересиланні ссилки статті (або сщц шарінг статті) нехай підтягується відповідна картинка з списку статтей ( https://webdevelop.pro/blog-list.html )
![2017-12-11 14 35 50](https://user-images.githubusercontent.com/20995691/33831411-b7574fc2-de80-11e7-8def-56ee3d237f37.png)

- [x] аналогічно, якщо надсилаєш ссилку проекту, то нехай тягнеться його картинка із списку проектів https://webdevelop.pro/portfolio.html
![2017-12-11 14 38 06](https://user-images.githubusercontent.com/20995691/33831492-ee961c20-de80-11e7-9767-e69d08b586f6.png)

**Comment by vladyslav2** [comment]
@MariaKravchuk ээээ?!

**Comment by MariaKravchuk** [comment]
@vladyslav2 @OstapL не працює нічого зараз, перевіряйте ще раз
