### ISSUE TITLE
Add project of GF

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#29]
- [x] в скетч макеті я зробила як оформити GF 
https://drive.google.com/open?id=1c1TAGChBg5p5Ei4uaez3f9VAZEguAghj

- [x] для галереї картинки тут 
https://drive.google.com/open?id=1wl-6Bcx5wPrkHrD0uRlUpwGb1kswX-wx

- [x] фотки які йдуть по тексту ( не в галереї) ти можеш експортувати з скетча.

- [x] тексти теж бери з скетча

- [x] добавить фото/описание/тайтл в webpack для facebook

- [x] добавить cp фотки в deploy.sh

**Comment by vladyslav2** [comment]
- [ ] мне нужно обновить тексты
- [ ] добавить видео с кеном в слайдер

**Comment by vladyslav2** [comment]
- [ ] @MariaKravchuk давай обсудим дизайн страницы GF

**Comment by MariaKravchuk** [comment]
@OstapL поправте назву проекту в табі (в тайтлі)
GrowthFountain
![2017-12-17 14 43 11](https://user-images.githubusercontent.com/20995691/34079557-b753298a-e338-11e7-8bf4-2f2f9a787502.png)

**Comment by OstapL** [comment]
@MariaKravchuk змінив на GrowthFountain

**Comment by vladyslav2** [comment]
@MariaKravchuk добавил видео

**Comment by MariaKravchuk** [comment]
@OstapL я оновила скетч макет, ми там трохи змінили розмітку тільки для цього проекту

**Comment by OstapL** [comment]
@MariaKravchuk поправив розмітку
