### ISSUE TITLE
Навести порядок в папке src/img

### ISSUE THREAD

**Issue by vladyslav2** [OstapL/wdev#30]
- [x] все названия папок файлов нужно сделать с маленькой буквы
- [x] фото для проектов должны быть  в папке проекте, те preview положить в src/img/gallery/mlm-software/preview.jpg а не в src/img/gallery. Ну и файл переименовать в preview - иначе потом запутаемся что где
- [x] в папке gallery проекты назвать по названию ссылки те mlm-software в multi-level-marketing

- [x] обрати внимание в webpack.config.js есть ссылки на превью фото там тоже нужно будет поменять путь
- [x] deploy.sh там тоже нужно поменять название файлов

**Comment by vladyslav2** [comment]
@OstapL img/Favicon.ico, img/Favicon.svg давай с маленькой сделаем
16x16.png, 32x32.png - я не понял что за файлы сюда по названию можно перекинуть в папку default

**Comment by OstapL** [comment]
@vladyslav2 16x16.png, 32x32.png - это так же Favicon
со стороны верстки надо использовать стандартную фавиконку и 16/16 + 32/32 

я сделал как ты написал, перекинул в default

фавиконку поправил
