### ISSUE TITLE
СРОЧНО! Сделать ссылки другим цветом

### ISSUE THREAD

**Issue by vladyslav2** [OstapL/wdev#32]
https://webdevelop.pro/django-vs-aiohttp-perfomance-test.html

тут даже не видно что в тесте есть ссылки

и исправить типографику у вас это должно быть по умолчанию

**Comment by OstapL** [comment]
@vladyslav2 @MariaKravchuk 
Маш зробив по замовчуванням <a> таку як ти зробила для проекту GF
