### ISSUE TITLE
Single project page

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#5]
- [x] для **IOLinteractive** поміняй картинки з 2 по 5, я їх підправила трохи. Перша картинка норм, її залиш (та що вже на сайті)

картинки тут
https://drive.google.com/open?id=0B_i_rx2O2o8IOFdlX01qUm5UVjQ

остання картинка буде для відео. 
ссилка на відео тут
https://www.youtube.com/watch?v=Vdi4C7C6adU&list=PLlT7WHi69XceTN4G69LAF4Gmdc_NfnFUR&index=1

- [x] для **Multi-level marketing** зробила картинки також, ссилка https://drive.google.com/open?id=0B_i_rx2O2o8IaTdndkRweWRJU00

остання картинка для відео також, ссилка до нього: https://www.youtube.com/watch?time_continue=7&v=--zLfdqa5bI

також тут тексти 
https://drive.google.com/open?id=1QwHHRYGTWGAb8zipuNIGTq3Uvbuq90gohY346M8yC5w

- [x] картинки для Domain System
https://drive.google.com/open?id=0B6KvoKv0feJhWkh6cnNJOFBSdk0

текст

**Comment by MariaKravchuk** [comment]
- [ ] відцентруй картинки в галереї
![2017-11-02 14 52 02](https://user-images.githubusercontent.com/20995691/32326999-9aa1f7cc-bfdd-11e7-91bb-c2d7f2179dcc.png)

**Comment by OstapL** [comment]
@MariaKravchuk попрошу тебе зробити картинки одного розміру для multi-level-marketing

**Comment by MariaKravchuk** [comment]
@OstapL ок, зроблю. Я думала що зробила всі однакові, мабуть щось пропустила.

**Comment by ratmirasanov** [comment]
@MariaKravchuk, картинки уже готовы?

**Comment by MariaKravchuk** [comment]
@OstapL @ratmirasanov оновила на гугл драйві всі картинки

**Comment by OstapL** [comment]
@ratmirasanov @MariaKravchuk картинки оновив
