### ISSUE TITLE
[contact form] Update design and html after validation

### ISSUE THREAD

**Issue by vladyslav2** [OstapL/wdev#6]
@MariaKravchuk, @OstapL, при вводе неверных данных -- сообщения об ошибках появляются совсем неоформленные, без дизайна.

Нужно исправить.

**Comment by ratmirasanov** [comment]
#9 -- тут еще написал баги для формы со страницы Contacts. Они актыальны и для Web.

**Comment by vladyslav2** [comment]
@ratmirasanov пиши отдельно баги
потому что очень сложно читать когда такой список

**Comment by ratmirasanov** [comment]
@vladyslav2, добро.

**Comment by ratmirasanov** [comment]
@MariaKravchuk, по этому уже есть дизайн?
