### ISSUE TITLE
About

### ISSUE THREAD

**Issue by MariaKravchuk** [OstapL/wdev#7]
- [x] обрізала фотки і поміняла деякі. Треба оновити. Фото тут: https://drive.google.com/open?id=0B_i_rx2O2o8IOC0xUmJRWDI2b2c

- [x] вирівняти логотип із заголовками такими
![2017-11-03 14 03 27](https://user-images.githubusercontent.com/20995691/32373553-7f15f6a0-c0a2-11e7-9005-7d20dd467453.png)

- [x] з правого боку маленький відступ, а між фото і біографією виходить великий. Я знаю що в макеті не по сітці тут зроблено, але подивись чи ти можеш якось підсунути фото ближче до тексту, аби зменшити той проміжок
![2017-11-08 15 37 42](https://user-images.githubusercontent.com/20995691/32551976-0edadbe2-c49b-11e7-8aae-389467a2d0a9.png)

- [x] давай зробимо зростання лінії під іконками з ліва на право, як і самі іконки)
![2017-11-08 15 39 59](https://user-images.githubusercontent.com/20995691/32552020-36c71418-c49b-11e7-8802-5ac760e2ad79.png)

- [x] перевір тут тінь за макетом, її треба зробити з більшим опасіті мабуть
![2017-11-08 15 41 04](https://user-images.githubusercontent.com/20995691/32552050-53535178-c49b-11e7-832d-ffd4f88b834c.png)

- [x] тут через збільшення шрифту все трохи поїхало - подивись що там
![2017-11-08 15 42 02](https://user-images.githubusercontent.com/20995691/32552095-79f85d82-c49b-11e7-8677-bcfc14b3c820.png)

- [x] поміняй тут текст на цей 
**We’re always looking for inspiration for the great ideas by working, traveling and having fun**

![2017-11-08 15 43 32](https://user-images.githubusercontent.com/20995691/32552180-b8dcad82-c49b-11e7-8e97-9c22ff21a377.png)

**Comment by MariaKravchuk** [comment]
- [ ] заміни тут фотку - я поправила
![2017-11-10 19 21 03](https://user-images.githubusercontent.com/20995691/32670448-7bafb2da-c64c-11e7-8ebe-f2880c262064.png)

- [ ] заміни Ратміра фотку, там мій малий косяк був)
![2017-11-10 19 21 16](https://user-images.githubusercontent.com/20995691/32670468-8ca52e94-c64c-11e7-957f-c91fe4b15fe7.png)

- [ ] треба поправити паддінги, зверху і знизу зроби по 38( тут був мій косяк в макеті). І все є хотілося б ще більший відступ зліва, приблихно однаковий як відступ по середині. Хочеться звести відступи з права/середини/ліва до однакового значення, бо погано виглядає. 
![2017-11-10 19 21 33](https://user-images.githubusercontent.com/20995691/32670486-95ed5f76-c64c-11e7-9667-34153e6afbce.png)

- [ ] Давай розберемося з цими заголовками і відступами тут. 
- Зверху над н2 80 пкс
- знизу під полоскою - 80 пкс
- під заголовком н2 - 30 пкс 
- між сірим текстом і лінією - 30 пкс


![2017-11-10 18 55 37](https://user-images.githubusercontent.com/20995691/32670577-df965696-c64c-11e7-80b8-2946530461e9.png)

**Comment by ratmirasanov** [comment]
@MariaKravchuk, этот тикет нельзя закрыть уже? Или есть что-то недоделанное?
