### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by ratmirasanov** [OstapL/wdev#9]
- [x] @OstapL, нужно поправить стрелочку в дропдауне -- сейчас их 2 и они накладываются друг на друга (на Андроиде в Хроме):
![screenshot_2017-11-08-19-17-22-235_com android chrome](https://user-images.githubusercontent.com/24833489/32561068-f966fb42-c4b3-11e7-92aa-11c066e101df.png)
- [x] @vladyslav2, сообщение об ошибке для email помнять на "Not a valid email address." и заканчивать предложения точкой:
![screenshot_2017-11-08-19-17-30-051_com android chrome](https://user-images.githubusercontent.com/24833489/32561135-2c9cc712-c4b4-11e7-95af-fb641c7aacc9.png)
- [x] @vladyslav2, когда несколько раз жмем по кнопке Send -- сообщения об ошибках дублируются:
![screenshot_2017-11-08-19-17-39-618_com android chrome](https://user-images.githubusercontent.com/24833489/32561313-b0210db4-c4b4-11e7-9c52-16b9293a1ac4.png)
- [x] @OstapL, переименуй плейсхолдер на "Email" и название кнопки на "Ok" (те с большой буквы):
![screenshot_2017-11-08-19-17-59-056_com android chrome](https://user-images.githubusercontent.com/24833489/32561534-1a13d40e-c4b5-11e7-9330-b32d5a951313.png)
- [x] @vladyslav2, переименуй тайт листа на "Webdevelop.pro" и я бы убрал весь текст после "Thank you...":
![screenshot_2017-11-08-19-18-33-920_com android chrome](https://user-images.githubusercontent.com/24833489/32561633-67b3ad88-c4b5-11e7-807d-16a0ee22a3e6.png)
**Хз, как сейчас проверить.**
- [x] @OstapL, верстка расползлась на старнице "Contacts":
![screenshot_2017-11-08-19-22-43-719_com android chrome](https://user-images.githubusercontent.com/24833489/32561708-9924f76e-c4b5-11e7-8f35-119acae06456.png)
![screenshot_2017-11-08-19-22-48-752_com android chrome](https://user-images.githubusercontent.com/24833489/32561711-9b842da4-c4b5-11e7-95c8-3c7f68c3916b.png)
- [x] @OstapL, кнопки "Previous" и "Next" не работают:
![screenshot_2017-11-08-19-24-23-368_com android chrome 1](https://user-images.githubusercontent.com/24833489/32561841-ec312a40-c4b5-11e7-91d2-3274ca17a2c2.png)
- [x] @OstapL, стрелка накладывается на текст:
![screenshot_2017-11-08-19-24-45-537_com android chrome](https://user-images.githubusercontent.com/24833489/32561902-0bcbcd1a-c4b6-11e7-92f3-4e725c7656e6.png)
- [x] @OstapL, на странице конкретного проекта расползлась верстка:
![screenshot_2017-11-08-19-25-35-488_com android chrome](https://user-images.githubusercontent.com/24833489/32561950-2bb4b90c-c4b6-11e7-840c-448143de817d.png)

**Comment by OstapL** [comment]
@ratmirasanov 
нужно поправить стрелочку в дропдауне -- сейчас их 2 и они накладываются друг на друга: - хз Ратмир ) я не вижу такого ) надо что бы кто то еще проверил )
иначе могу спихнуть на твой китай ) 
не в обиду сказал )

**Comment by ratmirasanov** [comment]
@OstapL, а тебе не видно на скриншоте?

**Comment by ratmirasanov** [comment]
@OstapL, у тебя есть ко мне вопросы по 1 пункту?

**Comment by OstapL** [comment]
@ratmirasanov я не могу это поправить так как не вижу такого ;( 
смотрел на разных телефонах ) это по пункту 1 )
